---
title: "Lab 00 - Hello IDS!"
author: "Ziye Yang"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Tommy", "Saleh", "Nihad", 
           "Dominik", "Jeonghy"),
  github_username = c("Tommy-Rollins", "salhemammadzada", "Nihad457", 
                      "Dominiklaska8", "username 4"), 
  colour = c("purple", "red", "white", 
             "purple", "blue"),
  hobby = c("running", "football", "reading", 
            "reading", "watchingmovies"),
  favourite_number = c(2, 4, 5, 8, 7)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

*All Good*

